name: Deploy Rotanika

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
jobs:
  build-rotanika:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Update pip
      run: python -m pip install --upgrade pip
    
    - name: Install dependencies
      run: python -m pip install -r requirements.txt

    - name: Build Rotanika
      run: poe build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rotanika-${{ matrix.os }}
        path: dist/*

  build-rotanika_mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Rotanika
      run: poe build:mac

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: rotanika-macos-latest
        path: dist/*
  
  deploy-rotanika:
    needs: 
      - build-rotanika
      - build-rotanika_mac
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: rotanika-*/*
          tag_name: ${{ inputs.tag }}
          name: "Rotanika ${{ inputs.tag }}"
          body: "Multi-platform release for Rotanika ${{ inputs.tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
